# 1. Numpy

* 수학, 과학 계산용 패키지
* 성능: 파이썬의 리스트보다 빠름
* 메모리 사이즈: 파이썬의 리스트보다 적은 메모리를 사용
* 빌트인 함수: 선형대수, 통계관련 여러 함수들을 내장

In [1]:
# install numpy
!pip install numpy

In [2]:
import numpy as np

### 1-1. array 배열
* 여러 값들의 그룹

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr) # numpy.ndarray = n dimension array

numpy.ndarray

In [8]:
list1 = [1,2,3,4]
list2 = [[1,2,3,4],[5,6,7,8]]
print(list1)
print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [9]:
# create list to ndarray
arr1 = np.array(list1)
arr2 = np.array(list2)

In [10]:
print(arr1)
print(type(arr1))
print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [11]:
arr1.shape

(4,)

In [12]:
arr2.shape

(2, 4)

### 1-2. array의 data type
* ndarray는 list와 다르게 1개의 단일 데이터 타입만 허용

In [18]:
list1 = [1, 3.14, 14, 'python', '1234', True ]

In [14]:
list1

[1, 3, 14, 'python', '1234', True]

In [15]:
list1[3]

'python'

In [20]:
arr1 = np.array(list1)

In [23]:
arr1 # 데이터 타입이 바뀜; 정수 실수 모두 다 스트링으로 바꼈음

array(['1', '3.14', '14', 'python', '1234', 'True'], dtype='<U32')

In [25]:
# int와 float 타입이 같이 존재하는 경우, int로 설정
arr2 = np.array([1, 2, 3.14, 4], dtype=int)
arr2

array([1, 2, 3, 4])

In [27]:
# arr5 = np.array(list1, dtype=int)
# ValueError: invalid literal for int() with base 10: 'python'

Note:
* '1234'는 1234로 int로 바꿀 수 있음
* True, False는 1, 0으로 바꿀 수 있음

### 1-3 Slicing 슬라이싱

In [30]:
arr1 = np.array(["❤️", "🌸", "😍", "💕"])
arr1.shape

(4,)

In [31]:
print(arr1[0])
print(arr1[2])
print(arr1[0:2])
print(arr1[:3])
print(arr1[2:])

❤️
😍
['❤️' '🌸']
['❤️' '🌸' '😍']
['😍' '💕']


In [33]:
arr2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr2d.shape # (row, col)

(3, 4)

In [34]:
arr2d[0,2] # [row, col]

3

In [36]:
arr2d[2,1] #[row, col]

10

In [37]:
# 0행 (0th row)을 가져오기
print(arr2d[0])
print(arr2d[0, ])
print(arr2d[0,:])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [39]:
# 1열 (1st col)을 가져오기
# print(arr2d[,1]) # SyntaxError: invalid syntax
print(arr2d[:,1])

[ 2  6 10]


In [41]:
arr2d[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
arr2d[:1,2:]

array([[3, 4]])

In [44]:
arr2d[:1,:2]

array([[1, 2]])

### 1-4 Fancy 인덱싱
* 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [47]:
arr1 = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])
idx = [1,3,5]

In [46]:
arr1[idx]

array([23,  7, 65])

In [48]:
arr2d[[0,1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1-5 Boolean 인덱싱
* 조건 필터링을 통하여 Boolean 값을 이용한 인덱싱

In [49]:
arr1 = np.array(["❤️", "🌸", "😍", "💕"])

In [52]:
selValue = [True, True, False, False]

In [53]:
arr1[selValue]

array(['❤️', '🌸'], dtype='<U2')

In [54]:
arr2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [55]:
arr2d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
arr2d[arr2d > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

# 2. Matrix 연산

### 2-1. Matrix
* 행 (row) + 열 (column)
* 데이터분석 및 머신러닝은 행렬을 제외하고 연산할 수 없음

### 2-2 연산자

In [62]:
# 덧셈 연산
a = np.array([[1,2,3], [2,3,4]])
b = np.array([[3,4,5], [1,2,3]])

In [63]:
a.shape, b.shape

((2, 3), (2, 3))

In [65]:
# shape이 같다면 같은 position끼리 연산
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [66]:
# dot product (내적)
a = np.array([[1,2,3],
              [1,2,3],
              [2,3,4]])
b = np.array([[1,2],
              [3,4],
              [5,6]])

In [67]:
a.shape, b.shape

((3, 3), (3, 2))

In [69]:
# dot product (내적) (Matrix mulitplication)의 규칙
# 맞닿는 shape가 같아야 함
# ex) 앞의 col과 뒤의 row의 dimension이 같아야함
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])

### 2-6 arange
* 순차적인 값을 생성할 때 사용

In [71]:
arr1 = np.arange(1,11) #1부터 11 미만
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr1 = np.arange(start=1, stop=11, step=2)
arr1

array([1, 3, 5, 7, 9])

### 2-7 정렬 sort

In [78]:
arr1 = np.array([1, 10, 5, 8, 2, 4, 3, 6, 7, 9])
arr1

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [79]:
np.sort(arr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
np.sort(arr1)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [81]:
# sort는 보여줄때만 보여주는것이지 저장이 되는것이 아님
arr1

array([ 1, 10,  5,  8,  2,  4,  3,  6,  7,  9])

In [82]:
result = np.sort(arr1)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr2d = np.array([[3,11,12,1], [11,6,9,3], [9,10,0,1]])

In [90]:
# 행 정렬 row sort
np.sort(arr2d, axis=0)

array([[ 3,  6,  0,  1],
       [ 9, 10,  9,  1],
       [11, 11, 12,  3]])

In [91]:
# 열 정렬
np.sort(arr2d, axis=1)

array([[ 1,  3, 11, 12],
       [ 3,  6,  9, 11],
       [ 0,  1,  9, 10]])

In [92]:
# 마지막 방향
np.sort(arr2d, axis=-1)

array([[ 1,  3, 11, 12],
       [ 3,  6,  9, 11],
       [ 0,  1,  9, 10]])

### 2-8 숫자의 단일 연산

In [93]:
a = np.array([[1,2,3],
              [1,2,3],
              [2,3,4]])
b = np.array([[1,2],
              [3,4],
              [5,6]])

In [94]:
a + 3

array([[4, 5, 6],
       [4, 5, 6],
       [5, 6, 7]])

In [95]:
b * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])