# 1. 텐서플로우 Tensorflow

* 텐서플로우는 ML/DL 모델을 개발하고 학습시키는데 도움이 되는 핵심 오픈 소스 라이브러리
* 텐서플로우 2X에서는 케라스를 딥러닝 공식 API를 채택하였고 텐서플로우 내의 하나의 프레임워크로 개발되고 있음

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.12.0


### 1-1. Tensor
* Tensor는 multi-dimensional array를 나타내는 말
* Tensorflow의 기본 data type

In [ ]:
a = tf.constant([10,3], dtype=tf.float32)
print(a)
# a라는 변수는 tensor라는 데이터 타입이고, 2개의 데이터를 가지고 있는 1차원의 배열

b = tf.constant('Hello Tensorflow!')
print(b)

tf.Tensor([10.  3.], shape=(2,), dtype=float32)
tf.Tensor(b'Hello Tensorflow!', shape=(), dtype=string)


In [ ]:
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(c)
print(type(c))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
import numpy as np

In [ ]:
x_np = np.array([[1.0,2.0],
                 [3.0,4.0]])

x_list = [[1.0, 2.0],
          [3.0,4.0]]

print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# ndarray를 tensor로 변환
x_np_tf = tf.convert_to_tensor(x_np)
print(type(x_np_tf))

# list를 tensor로 변환
x_list_tf = tf.convert_to_tensor(x_list)
print(type(x_list_tf))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# tensor를 numpy의 ndarray로 변환
print(x_np_tf.numpy())
print(type(x_np_tf.numpy()))

[[1. 2.]
 [3. 4.]]
<class 'numpy.ndarray'>


### 1-2. tensorflow 함수

In [ ]:
a = tf.ones((2,3))
print(a)

b = tf.zeros((2,3))
print(b)

c = tf.fill((2,3), 10)
print(c)

d = tf.zeros_like(c) # parameter로 전달된 텐서 행렬을 복사하여 같은 shape의 행렬을 생성, but 데이터는 복사하지 않음
print(d)

e = tf.ones_like(c)
print(e)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[10 10 10]
 [10 10 10]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [ ]:
g = tf.range(10)
print(g)



tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
# 0에서 1사이의 랜덤한 값을 2행 2열로 추출해라
# 나중에 가중치 값을 구할때 용이하게 쓰임
h = tf.random.uniform((2,2))
print(h)

# 정규분포 normal distribution 난수 random number를 2행2열로 추출
i = tf.random.normal((2,2))
print(i)

tf.Tensor(
[[0.5739149  0.73336875]
 [0.9520148  0.45838296]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2.1152778   0.20618252]
 [ 0.20503744  0.13860844]], shape=(2, 2), dtype=float32)


### 1-3. Tensor의 속성

In [ ]:
tensor = tf.random.normal((3,4))
print(f'shape: {tensor.shape}')
print(f'DataType: {tensor.dtype}')

shape: (3, 4)
DataType: <dtype: 'float32'>


In [ ]:
# tensor reshape
tensor = tf.reshape(tensor, (4,3))
print(f'Shape: {tensor.shape}')

# tensor change data type
tensor = tf.cast(tensor, tf.int32)
print(f'DataType: {tensor.dtype}')

Shape: (4, 3)
DataType: <dtype: 'int32'>


### 1-4. Variable
* Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서
* 딥러닝에서는 학습해야 하는 가중치 (weight, bias)들을 variable로 생성

In [ ]:
tensor = tf.ones((3,4))
print(tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [ ]:
# tensor[0,0] = 100 # TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
# 기존 텐서를 variable 형태로
var = tf.Variable(tensor)
print(var)

# assign(): variable에 값을 설정
var[0,0].assign(100)
print(var)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[100.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]], dtype=float32)>


In [ ]:
value1 = tf.random.normal(shape=(2,2))
value1 = tf.Variable(value1)
print(value1)

value2 = tf.random.normal(shape=(2,2))
print(value2)
value1.assign(value2)
print(value1)

# assign_add(): variable에 값을 더해주는 함수
# 특징: shape가 같아야 사용 가능
value3 = tf.ones(shape=(2,2))
value1.assign_add(value3)
print(value1)

value1.assign_sub(value3)
print(value1)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.0661228 , -0.5944078 ],
       [-0.31873435, -1.9660162 ]], dtype=float32)>
tf.Tensor(
[[-0.5307876   0.93050987]
 [ 0.78087246 -1.3766261 ]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.5307876 ,  0.93050987],
       [ 0.78087246, -1.3766261 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.4692124 ,  1.9305098 ],
       [ 1.7808725 , -0.37662613]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.5307876 ,  0.9305098 ],
       [ 0.78087246, -1.3766261 ]], dtype=float32)>


### 1-5. Indexing & slicing

In [ ]:
a = tf.range(1,13)
print(a)

a = tf.reshape(a, (3,4))
print(a)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [ ]:
# 인덱싱을 하면 차원이 감소하게 됨
print(a[1]) # 뽑아온 데이터만큼의 차원이 뽑힘
print(a[0,-1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# 슬라이싱은 차원 유지
print(a[1:-1]) # 차원은 유지하되 데이터를 뽑아옴
print(a[:2, 2:])

tf.Tensor([[5 6 7 8]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


### 1-6. 차원 바꾸기

In [ ]:
a = tf.range(16)
print(a)

# (2개의 matrix, 2 rows, automated columns)
a = tf.reshape(a, (2,2,-1))  # -1 자동으로 만들라는 뜻
print(a)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


In [ ]:
 # transpose(): 행렬의 차원을 인덱스로 변환
 # a는 2 matrix, 2행, 4의 shape (2,2,4)
 # 이 shape을 리스트로 보았을때, 인덱스0 = 2, 인덱스1 = 2, 인덱스2 = 4
 # 따라서, transpose(2,0,1)은 인덱스를 따라 shape이 (4,2,2)가 됨
 b = tf.transpose(a, (2,0,1))
 print(b)

tf.Tensor(
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]], shape=(4, 2, 2), dtype=int32)


### 1-7. Tensor 연산

In [ ]:
x = tf.constant([[1,2], [3,4]], dtype=tf.float32)
y = tf.constant([[1,2], [3,4]], dtype=tf.float32)
print(x)
print(y)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [ ]:
print(tf.add(x,y))
print(tf.subtract(x,y))
print(tf.multiply(x,y))
print(tf.divide(x,y))
print(tf.matmul(x,y))

tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 7. 10.]
 [15. 22.]], shape=(2, 2), dtype=float32)


In [ ]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)

tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 7. 10.]
 [15. 22.]], shape=(2, 2), dtype=float32)


In [ ]:
z = tf.range(1,11)
z = tf.reshape(z, (2,5))
print(z)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [ ]:
# reduce_sum(): 요소의 합계를 구함
print(tf.reduce_sum(z))

tf.Tensor(55, shape=(), dtype=int32)


In [ ]:
# 축을 설정하면 축에 대해서 합계를 함
sum1 = tf.reduce_sum(z, axis=0) # 행 (column)
print(sum1)

sum2 = tf.reduce_sum(z, axis=1) # 열 (row)
print(sum2)

sum3 = tf.reduce_sum(z, axis=-1) # 해당 차원의 마지막 방향 (열)
print(sum3)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)


In [ ]:
# concat(): 행과 열을 합침
concat1 = tf.concat([z,z], axis=0) # 열 밑으로
print(concat1)

concat2 = tf.concat([z,z], axis=1) # column 옆으로
print(concat2)

concat3 = tf.concat([z,z], axis=-1) # 마지막 방향에 대해
print(concat3)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]], shape=(2, 10), dtype=int32)
