# 1. 파이토치 Pytorch

* tensorflow와 함께 머신러닝, 딥러닝에서 가장 널리 사용되는 framework
* 초기에는 Torch라는 이름으로 Lua언어 기반으로 만들어졌으나, 이후 Python 기반으로 변경한 것이 Pytorch
* NYU와 Facebook이 공동으로 개발하였고, 현재 가장 대중적이고 널리 사용되는 framework

In [ ]:
import torch

In [ ]:
# !pip install tensorflow-cpu  # cpu 버전
# !pip install tensorflow      # gpu 버전 (사용이 그래픽카드에 따라 다름)

In [ ]:
print(torch.__version__)

2.0.1+cu118


### 1-1 Tensor
* 텐서는 배열이나 행렬과 매우 유사한 특수 자료구조
* 파이토치는 텐서를 사용하여 모델의 입력과 출력, 모델의 매개변수들을 부호화함

In [ ]:
data = [[1,2],
        [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
import numpy as np

In [ ]:
# tensor()
np_array = np.array(data)
x_np_1 = torch.tensor(np_array)
print(x_np_1)

tensor([[1, 2],
        [3, 4]])


In [ ]:
# 텐서플로우와 다르게 Variable을 사용하지 않아도 데이터를 바꿀 수 있음
x_np_1[0,0] = 100
print(x_np_1)

tensor([[100,   2],
        [  3,   4]])


In [ ]:
# as_tensor(): 동일한 메모리 주소를 가리키는 뷰를 만듬
# as_tensor를 사용시 np_array의 주소가 동일하므로, 데이터를 바꾸면 같이 바뀜
x_np_2 = torch.as_tensor(np_array)
print(x_np_2)

tensor([[1, 2],
        [3, 4]])


In [ ]:
x_np_2[0,0] = 200
print(x_np_2)
print(np_array)

tensor([[200,   2],
        [  3,   4]])
[[200   2]
 [  3   4]]


In [ ]:
# from_numpy() : 동일한 메모리 주소를 가리키는 뷰를 만듬
x_np_3 = torch.from_numpy(np_array)
print(x_np_3)

tensor([[200,   2],
        [  3,   4]])


In [ ]:
x_np_3[0,0] = 300
print(x_np_3)
print(np_array)

tensor([[300,   2],
        [  3,   4]])
[[300   2]
 [  3   4]]


In [ ]:
np_again = x_np_1.numpy()
print(np_again, type(np_again))

[[100   2]
 [  3   4]] <class 'numpy.ndarray'>


In [ ]:
a = torch.ones(2,3)
print(a)

b = torch.zeros(2,3)
print(b)

# tf.fill과 동일
c = torch.full((2,3), 2)
print(c)

# tf.random.normal과 동일 (0,1사이의 normal distribution randomly selected)
d = torch.empty(2,3)
print(d)

# identity matrix
e = torch.eye(3)
print(3)

f = torch.arange(10)
print(f)

# 0 < x < 1 사이의 random number
g = torch.rand(2,2)
print(g)

# tf.random.normal과 동일
h = torch.randn(2,2)
print(h)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[1.8712e-02, 3.3427e-41, 1.5863e-42],
        [0.0000e+00, 1.8712e-02, 3.3427e-41]])
3
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0.6846, 0.2110],
        [0.4273, 0.9894]])
tensor([[-1.0263,  0.2488],
        [-0.9874,  1.8053]])


### 1-2. Tensor의 속성

In [ ]:
tensor = torch.rand(3,4)
print(f'shape: {tensor.shape}')
print(f'type: {tensor.dtype}')
print(f'device: {tensor.device}')

shape: torch.Size([3, 4])
type: torch.float32
device: cpu


### 1-3. GPU 사용하기
* 코랩에서는 device를 변경하여 gpu 연산도 가능
  * 메뉴 런타임 -> 런타임 유형 변경 -> 하드웨어 가속기를 GPU 변경 -> 런타임 다시 시작


In [ ]:
tensor = torch.rand(4,3)
tensor = tensor.int()

# cuda : gpu
# is_availbe(): 사용할 수 있는
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f'shape: {tensor.shape}')
print(f'type: {tensor.dtype}')
print(f'device: {tensor.device}')

shape: torch.Size([4, 3])
type: torch.int32
device: cuda:0


### 1-4 Indexing & Slicing

In [ ]:
a = torch.arange(1,13).reshape(3,4)
print(a)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [ ]:
print(a[1]) # indexing, 차원이 낮아짐

tensor([5, 6, 7, 8])


In [ ]:
print(a[0,-1]) # indexing, 또한 차원이 낮아짐

tensor(4)


In [ ]:
print(a[1:-1]) # slicing, 차원은 동일

tensor([[5, 6, 7, 8]])


In [ ]:
print(a[:2,2:])

tensor([[3, 4],
        [7, 8]])


### 1-5. Transpose

In [ ]:
a = torch.arange(16).reshape(2,2,4)
print(a, a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]) torch.Size([2, 2, 4])


In [ ]:
b = a.transpose(1,2)
print(b, b.shape)

tensor([[[ 0,  4],
         [ 1,  5],
         [ 2,  6],
         [ 3,  7]],

        [[ 8, 12],
         [ 9, 13],
         [10, 14],
         [11, 15]]]) torch.Size([2, 4, 2])


### 1-6. Permute

In [ ]:
c = a.permute((2,0,1))
print(c, c.shape)

tensor([[[ 0,  4],
         [ 8, 12]],

        [[ 1,  5],
         [ 9, 13]],

        [[ 2,  6],
         [10, 14]],

        [[ 3,  7],
         [11, 15]]]) torch.Size([4, 2, 2])


### 1-7. Tensor 연산

In [ ]:
x = torch.tensor([[1,2], [3,4]], dtype=torch.float32)
y = torch.tensor([[5,6], [7,8]], dtype=torch.float32)
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [ ]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [ ]:
print(torch.add(x,y))
print(torch.subtract(x,y))
print(torch.multiply(x,y))
print(torch.divide(x,y))
print(torch.matmul(x,y))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [ ]:
# in-place 연산
# num += 1
print(x.add(y))
print(x)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(x.add_(y)) # x에 결과를 다시 저장
print(x) # x가 값이 위 box와 다르게 변함

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])


In [ ]:
z = torch.arange(1,11).reshape(2,5)
print(z)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [ ]:
sum1 = torch.sum(z, axis=0) # row
print(sum1, sum1.shape)

tensor([ 7,  9, 11, 13, 15]) torch.Size([5])


In [ ]:
sum2 = torch.sum(z, axis=1) # col
print(sum2, sum2.shape)

tensor([15, 40]) torch.Size([2])


In [ ]:
sum3 = torch.sum(z, axis=-1) # 마지막 방향, which is col
print(sum3, sum3.shape)

tensor([15, 40]) torch.Size([2])


In [ ]:
a = torch.arange(24).reshape(4,6)
b = a.clone().detach() # ctrl C. ctrl V 개념
print(a, a.shape)
print(b, b.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) torch.Size([4, 6])
